name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build coe
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."
