name: Issues
on: issues
jobs:
  issues:
    runs-on: windows-latest
    steps:
      - name: Event details
        run: echo "Event details"
      - name: Get all events from GitHub
        run: echo "${{ toJSON(github) }}"
